ALTER TABLE Teams
ADD CONSTRAINT coach_persons
FOREIGN KEY (coachID) REFERENCES Persons (personID)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE GamePlayers
ADD CONSTRAINT gameplayers_games
FOREIGN KEY (gameID) REFERENCES Games (gameID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE GamePlayers
ADD CONSTRAINT gameplayers_player
FOREIGN KEY (playerID) REFERENCES Players (playerID)
ON DELETE RESTRICT
ON UPDATE CASCADE;
